### ISSUE TITLE
where is the config.toml file?

### ISSUE THREAD

**Issue by saseiler** [Azure-Samples/IoT-Edge-K8s-KubeVirt-Deployment#2]
Per the tutorial and video, the user should copy the config.toml file and change the connection string to the users iot hub device id, but I do not see a config.toml file in this repo? Where is it?

**Comment by veyalla** [comment]
Here is an example of a minimal one: https://github.com/Azure/iotedge-vm-deploy/blob/1.2/config.toml (insert your connection string at line 3)
