### ISSUE TITLE
Deploying IoT Edge VM Helm install not working

### ISSUE THREAD

**Issue by NishantThakkar** [Azure-Samples/IoT-Edge-K8s-KubeVirt-Deployment#3]
I am following mentioned steps in readme.
Facing issue with **step 3 under section Deploying IoT Edge VM**.

**Below steps I did:**

1. Created RSA key and copied config.toml from /etc/aziot/config.toml to /IoT-Edge-K8s-KubeVirt-Deployment/deployment/helm.
2. Went till /IoT-Edge-K8s-KubeVirt-Deployment/deployment/helm
3. Executed below command
`sudo helm install --generate-name . --set publicSshKey="$(cat ~/.ssh/id_rsa.pub)",aziotEdgeVmEnableExternalSsh=true,aziotEdgeVmDiskSize=4Gi,nameOverride=aziot-edge-kubevirt,macAddress=fe:7e:48:a0:7d:22 --set-file azIotEdgeConfig=config.toml
`

Getting below error message:

> **INSTALLATION FAILED:** Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp 127.0.0.1:8080: connect: connection refused

**Kubernetes run on port 6443, then why it's trying to check on port 8080?**

Thank you,
Nishant Thakkar.

**Comment by suneetnangia** [comment]
Hi @NishantThakkar, that looks like there's a problem with your connectivity to K8s cluster. Depending on where you have the Kubectl client installed, if you have it on WSL2, this cmd may help `export KUBECONFIG=/mnt/c/Users/<username>/.kube/config`
Connectivity to K8s is outside the scope of this repo, this link may help https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/
